// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUq1lK8jKx4ZqL9pYEgVsn5H3i9CMBekg',
    appId: '1:132663123215:web:397f8b96bb753e789eb27a',
    messagingSenderId: '132663123215',
    projectId: 'coinkids',
    authDomain: 'coinkids.firebaseapp.com',
    storageBucket: 'coinkids.appspot.com',
    measurementId: 'G-8J6Y3CB33X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-XsuWFVY58ULngZ3wKDY6dhv43NnA6WU',
    appId: '1:132663123215:android:30e45d10bc3060969eb27a',
    messagingSenderId: '132663123215',
    projectId: 'coinkids',
    storageBucket: 'coinkids.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWC962lMXQDpO2Rrvwxdz8JYb3K9duT7w',
    appId: '1:132663123215:ios:b3604c9591c047c39eb27a',
    messagingSenderId: '132663123215',
    projectId: 'coinkids',
    storageBucket: 'coinkids.appspot.com',
    androidClientId: '132663123215-goqti42t82dqpn9l2kbnuk00logc4a13.apps.googleusercontent.com',
    iosClientId: '132663123215-lsq3barps38onmbhdu1f32kc9u676i7q.apps.googleusercontent.com',
    iosBundleId: 'com.app.coinkids',
  );
}
